# Everything in this section will be available as an environment variable
NCBI_API_KEY = "d07c55ffe0e94ecee92244f0922fb6216808"
X_ELS_APIKey = "18cea8004848f339d14dd509a16e753e"
X_ELS_Insttoken = "aa8087d5506a067fa3e1c2761628f450"

# You can also add other sections if you like.
# The contents of sections as shown below will not become environment variables,
# but they'll be easily accessible from within Streamlit anyway as we show
# later in this doc.
[my_cool_secrets]
things_i_like = ["Streamlit", "Python"]